[package]
name = "Minecraft_Change_IME_for_Rust"
version = "0.1.0"
edition = "2021"

[dependencies]
windows = { version = "0.59.0", features = [
    "Win32_Foundation",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_UI_WindowsAndMessaging",
] }
